services:
  app:
    image: ghcr.io/ska-aleksej/autoline-parser:latest
    container_name: autoline-parser
    restart: unless-stopped
    user: 1500:1500
    environment:
      - MAIL_LOGIN=${MAIL_LOGIN}
      - MAIL_SENDER=${MAIL_SENDER}
      - MAIL_TOKEN=${MAIL_TOKEN}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_ADMIN_ID=${TELEGRAM_ADMIN_ID}
      - TELEGRAM_ALLOWED_IDS=${TELEGRAM_ALLOWED_IDS}
    volumes:
      - ./logs:/app/logs
      - ./db:/app/db
      - ./application.properties:/app/application.properties